### PR TITLE
Switch to Ruff formatter

### PR DESCRIPTION
**Pull request by hemmelig**
## What is the purpose of this Pull Request? 
Switch from Black to Ruff for code formatting. Further streamlines the tooling around the project. I also suspect there will be even more tooling for Python coming from this project (e.g. unit testing). One to watch for sure.

The switch caused zero lines of change in the `quakemigrate` package. I also applied the formatter to the examples scripts and the current test scripts, which had not been formatted.

The pre-commit hook was updated to use `ruff format` instead of `black`.

### Relevant Issues
No relevant Issues.

## Test cases
Purely formatting change—does not affect functionality/test results.

- [x] All examples run without any new warnings
- [x] test_benchmarks.py reports all example tests pass

### System details
macOS Monterey 12.5.1, Python 3.11

### Final checklist
- [x] Correct base branch selected?
    - `master` (if a bugfix/patch update)
    - `version/vX.X.X` if a new significant feature (discuss with developers)
- [x] All tests still pass.
- [x] Any new features or fixed regressions are covered by new tests.
- [x] Any new or changed features are fully documented.

### CODE REVIEW

**Review by TomWinder — APPROVED** [review]
Looks fine - haven't read through details of ruff vs black but happy to trust your judgement.

Only comment is that in a couple of places in the example scripts I wonder if the previous (not technically correct) layout was useful to make the individual settings easier to parse for a new user. Particularly:

```diff
-onset.bandpass_filters = {
-    "P": [10, 125, 4],
-    "S": [10, 125, 4]}
-onset.sta_lta_windows = {
-    "P": [0.01, 0.25],
-    "S": [0.05, 0.5]}
+onset.bandpass_filters = {"P": [10, 125, 4], "S": [10, 125, 4]}
+onset.sta_lta_windows = {"P": [0.01, 0.25], "S": [0.05, 0.5]}
```

This is a style thing really. Probably it's not the biggest barrier to entry right now so not something to be pre-occupied over, but interested to hear your opinion.

**Comment by TomWinder** [comment]
Also realised I fecked up the stack of PR's you had here - sorry about that... Will await what you think to be the wisest solution.

**Comment by hemmelig** [comment]
> Looks fine - haven't read through details of ruff vs black but happy to trust your judgement.
> 
> Only comment is that in a couple of places in the example scripts I wonder if the previous (not technically correct) layout was useful to make the individual settings easier to parse for a new user. Particularly:
> 
> ```diff
> -onset.bandpass_filters = {
> -    "P": [10, 125, 4],
> -    "S": [10, 125, 4]}
> -onset.sta_lta_windows = {
> -    "P": [0.01, 0.25],
> -    "S": [0.05, 0.5]}
> +onset.bandpass_filters = {"P": [10, 125, 4], "S": [10, 125, 4]}
> +onset.sta_lta_windows = {"P": [0.01, 0.25], "S": [0.05, 0.5]}
> ```
> 
> This is a style thing really. Probably it's not the biggest barrier to entry right now so not something to be pre-occupied over, but interested to hear your opinion.

Yeah, I feel the same about this one. Definitely clearer when split over multiple lines, but not sure there's a straightforward solution that wouldn't introduce exceptions elsewhere, where we don't want them. I'm going to merge for now, just to keep it rolling.

**Comment by hemmelig** [comment]
Aye, I've melted my brain with the order of all of this.

Plan to resolve:

Re-review this one, direct approve. I then squash and merge which turns this weirdness back into a single commit. I will copy over the text from the 9580ccf commit so it should all iron out the same.

I'll then re-target the other PRs (#166 and #168) at master. These two PRs still actually need a couple of bits tidying anyway then they're good to go.

**Review by TomWinder — APPROVED** [review]

**Pull request merged**
